### PR TITLE
replace sns report task

### PR DESCRIPTION
**Pull request by scisco**
This PR cannot be merged until `@cumulus/sf-sns-report` task is released

### CODE REVIEW

**Comment by scisco** [comment]
@jennyhliu the new sf-sns-report task fails the integration tests. Could you look at the config in this PR and see why it is failing?

**Comment by jennyhliu** [comment]
@scisco The validation error has been fixed in cumulus repo.  We need a new release of cumulus repo.

**Comment by scisco** [comment]
Thanks. I'll add a feature to the integration tests to get the code from the cumulus repo if it is not released

**Comment by scisco** [comment]
I'm going to move this PR to the cumulus repo after [this PR](https://github.com/cumulus-nasa/cumulus/pull/299) is merged.

**Pull request closed without merging**
